# Generated by Django 5.0.14 on 2025-04-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDetectionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the animal type (e.g., 'Amur Leopard')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'amur_leopard')", max_length=100, unique=True)),
                ('min_magnitude', models.FloatField(default=3500, help_text='Minimum magnitude threshold for detection')),
                ('max_magnitude', models.FloatField(default=10000, help_text='Maximum magnitude threshold for detection')),
                ('min_frequency', models.FloatField(default=15, help_text='Minimum frequency in Hz')),
                ('max_frequency', models.FloatField(default=300, help_text='Maximum frequency in Hz')),
                ('segment_duration', models.FloatField(default=0.1, help_text='Duration of each segment in seconds')),
                ('time_threshold', models.FloatField(default=5, help_text='Time threshold for merging events in seconds')),
                ('min_impulse_count', models.IntegerField(default=3, help_text='Minimum number of impulses to consider a valid saw call')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default parameter set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal Detection Parameters',
                'verbose_name_plural': 'Animal Detection Parameters',
            },
        ),
    ]
