# Generated by Django 5.0.14 on 2025-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0002_animaldetectionparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectednoiseaudiofile',
            name='noise_verified',
            field=models.BooleanField(default=True),
        ),
    ]
