# Generated by Django 5.0.14 on 2025-04-29 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0003_detectednoiseaudiofile_noise_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='database',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='animal_type',
            field=models.CharField(choices=[('amur_leopard', 'Amur Leopard'), ('amur_tiger', 'Amur Tiger')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='audio_file_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='recording_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='upload_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='zoo_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['status', 'uploaded_at'], name='vocalizatio_status_3eb2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='originalaudiofile',
            index=models.Index(fields=['animal_type', 'upload_date'], name='vocalizatio_animal__4227e1_idx'),
        ),
        migrations.AddIndex(
            model_name='originalaudiofile',
            index=models.Index(fields=['recording_date', 'animal_type'], name='vocalizatio_recordi_46a08d_idx'),
        ),
        migrations.AddIndex(
            model_name='zoo',
            index=models.Index(fields=['zoo_name'], name='vocalizatio_zoo_nam_60c0ff_idx'),
        ),
    ]
